### ISSUE TITLE
For base_task, task.run() will work with context if no structure is provided.

### ISSUE THREAD

**Issue by Chuan-Zh** [griptape-ai/griptape#1154]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Is your feature request related to a problem? Please describe.**
``` python
prompt_task = PromptTask(
    "Respond to the user's following question 'who are you' in the language '{{preferred_language}}' and tone '{{tone}}'.",
    context={"preferred_language": "ENGLISH", "tone": "PLAYFUL"},
)
```
if just create a task like this, the context will not filled in when prompt_task.run().

**Describe the solution you'd like**
the context for prompt_task work without a  structure.

in base_task.py
``` python 
    @property
    def full_context(self) -> dict[str, Any]:
        if self.structure:
            structure_context = self.structure.context(self)

            structure_context.update(self.context)

            return structure_context
        else:
            return self.context
```

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by collindutter** [comment]
Are you able to provide a fully reproducible example? With this example, I run into #1155 first:

```python
from griptape.tasks import PromptTask

prompt_task = PromptTask(
    "Respond to the user's following question 'who are you' in the language '{{preferred_language}}' and tone '{{tone}}'.",
    context={"preferred_language": "ENGLISH", "tone": "PLAYFUL"},
)

prompt_task.run()
```

```
Traceback (most recent call last):
  File "/Users/collindutter/Documents/griptape/griptape-playground/src/issues/1154.py", line 8, in <module>
    prompt_task.run()
  File "/Users/collindutter/Documents/griptape/griptape/griptape/tasks/prompt_task.py", line 81, in run
    message = self.prompt_driver.run(self.prompt_stack)
                                     ^^^^^^^^^^^^^^^^^
  File "/Users/collindutter/Documents/griptape/griptape/griptape/tasks/prompt_task.py", line 48, in prompt_stack
    memory = self.structure.conversation_memory
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'conversation_memory'
```

Thanks!

**Comment by Chuan-Zh** [comment]
Could not because I also run into the error, so i fix the exception myself and continued.
I just want to find the inner working of Task, if it is not supported to work alone, I could use a structure.
