### ISSUE TITLE
Anthropic not working with tools when stream=True

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#1444]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
Mert mentioned that he was running into an issue with Anthropic when using tools: https://discordapp.com/channels/1096466116672487547/1096466118048231579/1318018239745232998

I was able to reproduce the result with a simple example:

```python
from griptape.configs import Defaults
from griptape.configs.drivers import AnthropicDriversConfig
from griptape.structures import Agent
from griptape.tools import DateTimeTool

Defaults.drivers_config = AnthropicDriversConfig()
agent = Agent(tools=[DateTimeTool()], stream=True)

agent.run("What day is it?")
```

Gave me this result:

```bash
[12/16/24 14:23:50] INFO     ToolkitTask 6eff5ee3364e4debb27209b54bb5ed4e
                             Input: What day is it?
[12/16/24 14:23:53] ERROR    ToolkitTask 6eff5ee3364e4debb27209b54bb5ed4e
                             Invalid JSON input for ToolAction
                             Traceback (most recent call last):
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\common\promp
                             t_stack\contents\action_call_message_content.py", line 40, in from_deltas
                                 parsed_input = json.loads(json_input)
                                                ^^^^^^^^^^^^^^^^^^^^^^
                               File "C:\Program Files\Python312\Lib\json\__init__.py", line 346, in loads
                                 return _default_decoder.decode(s)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "C:\Program Files\Python312\Lib\json\decoder.py", line 337, in decode
                                 obj, end = self.raw_decode(s, idx=_w(s, 0).end())
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File "C:\Program Files\Python312\Lib\json\decoder.py", line 355, in raw_decode
                                 raise JSONDecodeError("Expecting value", s, err.value) from None
                             json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

                             The above exception was the direct cause of the following exception:

                             Traceback (most recent call last):
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\tasks\base_t
                             ask.py", line 158, in run
                                 self.output = self.try_run()
                                               ^^^^^^^^^^^^^^
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\tasks\toolki
                             t_task.py", line 176, in try_run
                                 result = self.prompt_driver.run(self.prompt_stack)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\common\decor
                             ators.py", line 18, in decorator
                                 Observability.observe(
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\observabilit
                             y\observability.py", line 36, in observe
                                 return driver.observe(call)
                                        ^^^^^^^^^^^^^^^^^^^^
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\drivers\obse
                             rvability\no_op_observability_driver.py", line 16, in observe
                                 return call()
                                        ^^^^^^
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\common\obser
                             vable.py", line 19, in __call__
                                 return self.func(*self.args, **self.kwargs)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\drivers\prom
                             pt\base_prompt_driver.py", line 81, in run
                                 for attempt in self.retrying():
                                                ^^^^^^^^^^^^^^^
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\tenacity\__init__.py"
                             , line 443, in __iter__
                                 do = self.iter(retry_state=retry_state)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\tenacity\__init__.py"
                             , line 376, in iter
                                 result = action(retry_state)
                                          ^^^^^^^^^^^^^^^^^^^
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\tenacity\__init__.py"
                             , line 398, in <lambda>
                                 self._add_action_func(lambda rs: rs.outcome.result())
                                                                  ^^^^^^^^^^^^^^^^^^^
                               File "C:\Program Files\Python312\Lib\concurrent\futures\_base.py", line 449, in result
                                 return self.__get_result()
                                        ^^^^^^^^^^^^^^^^^^^
                               File "C:\Program Files\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
                                 raise self._exception
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\drivers\prom
                             pt\base_prompt_driver.py", line 85, in run
                                 result = self.__process_stream(prompt_stack) if self.stream else self.__process_run(prompt_stack)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\drivers\prom
                             pt\base_prompt_driver.py", line 157, in __process_stream
                                 return self.__build_message(list(delta_contents.values()), usage)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\drivers\prom
                             pt\base_prompt_driver.py", line 170, in __build_message
                                 content.append(ActionCallMessageContent.from_deltas(action_deltas))
                                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                               File
                             "C:\Users\jason\Documents\GitHub\course-griptape-intro-steamroller\.venv\Lib\site-packages\griptape\common\promp
                             t_stack\contents\action_call_message_content.py", line 42, in from_deltas
                                 raise ValueError("Invalid JSON input for ToolAction") from exc
                             ValueError: Invalid JSON input for ToolAction
```

Setting `stream=False` returnd the appropriate response:

```bash
[12/16/24 14:24:34] INFO     ToolkitTask ce91cc50c94343a0ad5e1beafbafca7d
                             Input: What day is it?
[12/16/24 14:24:38] INFO     Subtask 616cf10a702e4eef8ff6f0e8d6dfaf30
                             Thought: To answer your question about what day it is, I'll need to use the DateTimeTool to get the current date
                             and time. Let me do that for you.
                             Actions: [
                               {
                                 "tag": "toolu_013LQPgVhdjrhstwtojbrU47",
                                 "name": "DateTimeTool",
                                 "path": "get_current_datetime",
                                 "input": {
                                   "values": {}
                                 }
                               }
                             ]
                    INFO     Subtask 616cf10a702e4eef8ff6f0e8d6dfaf30
                             Response: 2024-12-16 14:24:38.034419
[12/16/24 14:24:40] INFO     ToolkitTask ce91cc50c94343a0ad5e1beafbafca7d
                             Output: Based on the result from the DateTimeTool, the current date and time is 2024-12-16 14:24:38.034419.     

                             To answer your specific question about what day it is, I can interpret this for you:

                             Today is Monday, December 16, 2024.

                             Is there anything else you'd like to know about the current date or time?
```

**Comment by shhlife** [comment]
In addition, setting `use_native_tools=False` also allows it to work, regardless of Stream or not.
