### ISSUE TITLE
Support summary and summary index persistence in `SummaryConversationMemory`

### ISSUE THREAD

**Issue by vasinov** [griptape-ai/griptape#340]
In order to support `summary` and `summary_index` persistence in `SummaryConversationMemory`, I propose adding a `BaseSummaryConversationMemoryDriver` driver with `store` and `load` methods that will allow us to serialize and deserialize memory summary, summary index, and previous runs.

**Comment by collindutter** [comment]
Storing already appears to work:
```python
from griptape.drivers import LocalConversationMemoryDriver
from griptape.memory.structure import SummaryConversationMemory
from griptape.structures import Agent

agent = Agent(
    memory=SummaryConversationMemory(driver=LocalConversationMemoryDriver()),
)

agent.run("Hi my name is Collin.")
agent.run("My favorite color is blue")
```

griptape-memory.json
```
{
  "type": "SummaryConversationMemory",
  "runs": [
    {
      "id": "ec79b498891642f1957f044e47abd8a2",
      "input": "Hi my name is Collin.",
      "output": "Nice to meet you, Collin! How can I assist you today?"
    },
    {
      "id": "2f685d42370e444bbad76436d9e3de03",
      "input": "My favorite color is blue",
      "output": "That's great, Collin! Blue is a very calming and peaceful color. Is there anything specific you would like to know or discuss that involves the color blue?"
    }
  ],
  "offset": 1,
  "summary": "Collin introduces himself to the assistant and the assistant asks how they can help.",
  "summary_index": 1
}
```

But it fails on second run with autoload:
```
Traceback (most recent call last):
  File "/Users/collindutter/Documents/griptape/griptape-playground/src/issues/172.py", line 7, in <module>
    agent = Agent(logger_level=logging.DEBUG, memory=SummaryConversationMemory(driver=LocalConversationMemoryDriver()))
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<attrs generated init griptape.memory.structure.summary_conversation_memory.SummaryConversationMemory>", line 28, in __init__
  File "/Users/collindutter/Documents/griptape/griptape/griptape/memory/structure/conversation_memory.py", line 24, in __attrs_post_init__
    memory = self.driver.load()
             ^^^^^^^^^^^^^^^^^^
  File "/Users/collindutter/Documents/griptape/griptape/griptape/drivers/memory/conversation/local_conversation_memory_driver.py", line 20, in load
    memory = ConversationMemory.from_json(file.read())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/collindutter/Documents/griptape/griptape/griptape/memory/structure/conversation_memory.py", line 72, in from_json
    return ConversationMemory.from_dict(json.loads(memory_json))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/collindutter/Documents/griptape/griptape/griptape/memory/structure/conversation_memory.py", line 68, in from_dict
    return ConversationMemorySchema().load(memory_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/collindutter/Documents/griptape/griptape-playground/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
           ^^^^^^^^^^^^^^
  File "/Users/collindutter/Documents/griptape/griptape-playground/.venv/lib/python3.11/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'summary': ['Unknown field.'], 'summary_index': ['Unknown field.'], 'offset': ['Unknown field.']}
```
