### ISSUE TITLE
Got stack trace when trying to use dependencies_install_directory when instantiating a tool

### ISSUE THREAD

**Issue by shhlife** [griptape-ai/griptape#475]
- [ x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the bug**
I have a tool that has a dependency. I added the requirement to requirements.txt in the tool, then instantiated the tool with `dependencies_install_directory=True`. Got a stack trace:

```
Traceback (most recent call last):
  File "/Users/jason/Documents/griptape/griptape-shotgrid/app.py", line 17, in <module>
    sg = ShotGridTool(
         ^^^^^^^^^^^^^
  File "<attrs generated init shotgrid_tool.tool.ShotGridTool>", line 22, in __init__
  File "/Users/jason/Library/Caches/pypoetry/virtualenvs/griptape-shotgrid-3t4PnqOD-py3.11/lib/python3.11/site-packages/griptape/tools/base_tool.py", line 48, in __attrs_post_init__
    self.install_dependencies(os.environ.copy())
  File "/Users/jason/Library/Caches/pypoetry/virtualenvs/griptape-shotgrid-3t4PnqOD-py3.11/lib/python3.11/site-packages/griptape/tools/base_tool.py", line 169, in install_dependencies
    subprocess.run(
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 1883, in _execute_child
    self.pid = _fork_exec(
               ^^^^^^^^^^^
TypeError: expected str, bytes or os.PathLike object, not bool
```

**Comment by shhlife** [comment]
the `dependencies_intall_directory` takes a directory location, not a boolean. Specifying the directory fixes the stack trace issue.
