### ISSUE TITLE
Together AI support

### ISSUE THREAD

**Issue by LeventeNagy** [griptape-ai/griptape#512]
- [x] I have read and agree to the [contributing guidelines](https://github.com/griptape-ai/griptape#contributing).

**Describe the solution you'd like**
Ability to use TogetherAI with griptape

**Additional context**
I am a big fan of TogetherAI, I use it often, they offer a drop in open ai api replacement, but at the moment it doesn't seem to work

```
from griptape.structures import Agent
from griptape.drivers import OpenAiChatPromptDriver

agent = Agent(
    prompt_driver=OpenAiChatPromptDriver(
        api_key=os.environ["OPENAI_API_KEY"],
        base_url=os.environ["OPENAI_BASE_URL"],
        model="mistralai/Mixtral-8x7B-Instruct-v0.1",
        max_tokens=1024
    )
)
agent.run("Return the height and width of an average grown plant in cm, rounded to the closest 5cm: dianthus picotee mix")
```
When running it I am getting back the following error

```
Traceback (most recent call last):
  File "c:\projects\rl\app.py", line 18, in <module>
    agent = Agent(
            ^^^^^^
  File "<attrs generated init griptape.structures.agent.Agent>", line 40, in __init__
  File "C:\anaconda3\Lib\site-packages\griptape\structures\structure.py", line 53, in <lambda>
    default=Factory(lambda self: self.default_task_memory, takes_self=True), kw_only=True
                                 ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\griptape\structures\structure.py", line 126, in default_task_memory
    summary_engine=PromptSummaryEngine(prompt_driver=self.prompt_driver),
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<attrs generated init griptape.engines.summary.prompt_summary_engine.PromptSummaryEngine>", line 15, in __init__
  File "C:\anaconda3\Lib\site-packages\griptape\engines\summary\prompt_summary_engine.py", line 24, in <lambda>
    lambda self: TextChunker(tokenizer=self.prompt_driver.tokenizer, max_tokens=self.max_chunker_tokens),
                                                                                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\griptape\engines\summary\prompt_summary_engine.py", line 39, in max_chunker_tokens
    return round(self.prompt_driver.tokenizer.max_tokens * self.max_token_multiplier)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\griptape\tokenizers\openai_tokenizer.py", line 47, in max_tokens
    tokens = next(v for k, v in self.MODEL_PREFIXES_TO_MAX_TOKENS.items() if self.model.startswith(k))
```

I am wondering if this would be something considered in the future?

Thank you

**Comment by michal-repo** [comment]
@LeventeNagy  Just override Tokenizer class

```
import os
from griptape.structures import Agent
from griptape.drivers import OpenAiChatPromptDriver
from dotenv import load_dotenv
import openai
from griptape.tokenizers import OpenAiTokenizer
import logging
import tiktoken

load_dotenv()

client = openai.OpenAI(
    api_key=os.environ["OPENAI_API_KEY"],
    base_url=os.environ["OPENAI_BASE_URL"],
)


class MyOpenAiTokenizer(OpenAiTokenizer):
    MODEL_PREFIXES_TO_MAX_TOKENS = {
        "gpt-4-1106": 128000,
        "gpt-4-32k": 32768,
        "gpt-4": 8192,
        "gpt-3.5-turbo-16k": 16384,
        "gpt-3.5-turbo": 4096,
        "gpt-35-turbo-16k": 16384,
        "gpt-35-turbo": 4096,
        "text-davinci-003": 4097,
        "text-davinci-002": 4097,
        "code-davinci-002": 8001,
        "text-embedding-ada-002": 8191,
        "text-embedding-ada-001": 2046,
        "mistralai/Mixtral-8x7B-Instruct-v0.1": 8192,
    }

    def count_tokens(self, text: str | list, model: str | None = None) -> int:
        """
        Handles the special case of ChatML. Implementation adopted from the official OpenAI notebook:
        https://github.com/openai/openai-cookbook/blob/main/examples/How_to_count_tokens_with_tiktoken.ipynb
        """
        if isinstance(text, list):
            model = model if model else self.model

            try:
                encoding = tiktoken.encoding_for_model(model)
            except KeyError:
                logging.warning("model not found. Using cl100k_base encoding.")

                encoding = tiktoken.get_encoding("cl100k_base")

            if model in {
                "gpt-3.5-turbo-0613",
                "gpt-3.5-turbo-16k-0613",
                "gpt-4-0314",
                "gpt-4-32k-0314",
                "gpt-4-0613",
                "gpt-4-32k-0613",
                "mistralai/Mixtral-8x7B-Instruct-v0.1",
            }:
                tokens_per_message = 3
                tokens_per_name = 1
            elif model == "gpt-3.5-turbo-0301":
                # every message follows <|start|>{role/name}\n{content}<|end|>\n
                tokens_per_message = 4
                # if there's a name, the role is omitted
                tokens_per_name = -1
            elif "gpt-3.5-turbo" in model or "gpt-35-turbo" in model:
                logging.info("gpt-3.5-turbo may update over time. Returning num tokens assuming gpt-3.5-turbo-0613.")
                return self.count_tokens(text, model="gpt-3.5-turbo-0613")
            elif "gpt-4" in model:
                logging.info("gpt-4 may update over time. Returning num tokens assuming gpt-4-0613.")
                return self.count_tokens(text, model="gpt-4-0613")
            else:
                raise NotImplementedError(
                    f"""token_count() is not implemented for model {model}. 
                    See https://github.com/openai/openai-python/blob/main/chatml.md for 
                    information on how messages are converted to tokens."""
                )

            num_tokens = 0

            for message in text:
                num_tokens += tokens_per_message
                for key, value in message.items():
                    num_tokens += len(encoding.encode(value))
                    if key == "name":
                        num_tokens += tokens_per_name

            # every reply is primed with <|start|>assistant<|message|>
            num_tokens += 3

            return num_tokens
        else:
            return len(self.encoding.encode(text, allowed_special=set(self.stop_sequences)))


tokenizer = MyOpenAiTokenizer(model="mistralai/Mixtral-8x7B-Instruct-v0.1")
agent = Agent(
    prompt_driver=OpenAiChatPromptDriver(
        api_key=os.environ["OPENAI_API_KEY"],
        base_url=os.environ["OPENAI_BASE_URL"],
        model="mistralai/Mixtral-8x7B-Instruct-v0.1",
        max_tokens=1024,
        client=client,
        tokenizer=tokenizer,
        
    )
)
res = agent.run(
    "Return the height and width of an average grown plant in cm, rounded to the closest 5cm: dianthus picotee mix"
)
print(res.output_task.output.value)
```

.env
```
OPENAI_API_KEY="xxxxxxxxxxx"
OPENAI_BASE_URL="https://api.together.xyz/v1"
```

**Comment by collindutter** [comment]
Thank you for the issue @LeventeNagy! As @michal-repo pointed out, the issue lies in the `OpenAiTokenizer` not having support for `mistralai/Mixtral-8x7B-Instruct-v0.1`; overriding is a great solution for now. I am going to keep this issue open though as I think we need a more elegant way to deal with these drop-in clients.

**Comment by LeventeNagy** [comment]
@collindutter @michal-repo sorry for the slow response, thank you for both much appreciated 👍

**Comment by collindutter** [comment]
No worries @LeventeNagy, busy time of the year! We'll keep you posted on a solution here 🙂
